name: CI

on:
  schedule:
  - cron: "0 0 * * 7"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Generate new map
      run: |
        yarn install
        yarn build
    - name: Commit files
      run: |
        git config --local user.email "map@oaksandspokes.com"
        git config --local user.name "Oaks and Spokes"
        git commit -m "Update map on " -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
